### ISSUE TITLE
Download target-sysroot-1-darwin-macos.tar.gz failed

### ISSUE THREAD

**Issue by urakalee** [JetBrains/kotlinconf-app#24]
:checkKonanCompiler
:compileKonanLibsIphone
Downloading native dependencies (LLVM, sysroot etc). This is a one-time action performed only on the first run of the compiler.
Exception in thread "main" java.lang.IllegalStateException: Cannot download dependencies.
	at org.jetbrains.kotlin.native.interop.tool.ToolConfigKt.maybeExecuteHelper(ToolConfig.kt:66)
	at org.jetbrains.kotlin.native.interop.tool.ToolConfigKt.access$maybeExecuteHelper(ToolConfig.kt:1)
	at org.jetbrains.kotlin.native.interop.tool.ToolConfig.downloadDependencies(ToolConfig.kt:42)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processLib(main.kt:235)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:33)
	at org.jetbrains.kotlin.cli.utilities.MainKt.invokeCinterop(main.kt:90)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:112)
Caused by: org.jetbrains.kotlin.konan.util.DependencyDownloader$HTTPResponseException: Server returned HTTP response code: 403 for URL: https://download.jetbrains.com/kotlin/native/target-sysroot-1-darwin-macos.tar.gz
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.checkHTTPResponse(DependencyDownloader.kt:51)
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.tryDownload(DependencyDownloader.kt:128)
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.download(DependencyDownloader.kt:164)
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.download$default(DependencyDownloader.kt:142)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.processDependency(DependencyProcessor.kt:155)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.run(DependencyProcessor.kt:171)
	at org.jetbrains.kotlin.konan.util.Helper0.run(Helper0.kt:31)
	at org.jetbrains.kotlin.native.interop.tool.ToolConfigKt.maybeExecuteHelper(ToolConfig.kt:62)
	... 6 more
:compileKonanLibsIphone FAILED

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/blob/master/FAQ.md#q-how-do-i-run-kotlinnative-behind-a-corporate-proxy

**Comment by MarcinMoskala** [comment]
Due to the new Gradle plugin, this issue is outdated.
